### ISSUE TITLE
Appveyor build artifact is not a valid VSIX

### ISSUE THREAD

**Issue by VioletGiraffe** [VioletGiraffe/cppcheck-vs-addin#179]
![image](https://user-images.githubusercontent.com/1175926/35029379-614b9af2-fb63-11e7-9378-e14d5dccaaad.png)

```17.01.2018 8:49:31 - Microsoft VSIX Installer
17.01.2018 8:49:31 - -------------------------------------------
17.01.2018 8:49:31 - vsixinstaller.exe version:
17.01.2018 8:49:31 - 15.5.99+g87f89a485e
17.01.2018 8:49:31 - -------------------------------------------
17.01.2018 8:49:31 - Command line parameters:
17.01.2018 8:49:31 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\Downloads\CppcheckPlugin.vsix
17.01.2018 8:49:31 - -------------------------------------------
17.01.2018 8:49:31 - Microsoft VSIX Installer
17.01.2018 8:49:31 - -------------------------------------------
17.01.2018 8:49:31 - Initializing Install...
17.01.2018 8:49:31 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by VioletGiraffe** [comment]
@icnocop Any idea how to fix this? I've used Appveyor for C++ builds, but don't understand how it works for C#. For example, how to build the project with VS 2017 specifically?

**Comment by icnocop** [comment]
Appveyor has a separate build worker with Visual Studio 2017 installed, so in order to build a solution or project with a specific image, we'd have to specify it.

The image can be specified in at least two different ways, depending on whether there's a build matrix or not.

We can use the Appveyor web-based UI to generate a valid yml file.

For example, here is a version of appveyor.yml with Visual Studio 2017 build worker image explicitly specified:
```
version: 1.3.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: >-
    (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

    Vsix-IncrementVsixVersion ".\CPPCheckPlugin\source.extension.vsixmanifest" | Vsix-UpdateBuildVersion
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: .\CPPCheckPlugin\bin\**\*.vsix
```

**Comment by icnocop** [comment]
I think we have to explicitly build with devenv.exe instead of msbuild. I will have to test it.

**Comment by VioletGiraffe** [comment]
I just specified VS 2017 as you have suggested, and it works now. Not sure what the problem was, I didn't really expect building with VS 2017 instead of 2015 to magically help.

**Comment by icnocop** [comment]
Ok, great! :) 

Here's a reference for appveyor's build environment:
https://www.appveyor.com/docs/build-environment/

**Comment by VioletGiraffe** [comment]
Thanks! You're right, should have read it first.
